# Generated by Django 5.0.2 on 2024-03-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweetCocoWeb', '0002_rename_productid_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='Cupcake', max_length=50),
        ),
    ]
