# Generated by Django 5.0.2 on 2024-03-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweetCocoWeb', '0006_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
